# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'View/main_container/set_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(512, 688)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_name = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_name.setFont(font)
        self.label_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_name.setObjectName("label_name")
        self.verticalLayout_3.addWidget(self.label_name)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.label_nameStatus = QtWidgets.QLabel(Form)
        self.label_nameStatus.setText("")
        self.label_nameStatus.setObjectName("label_nameStatus")
        self.verticalLayout_3.addWidget(self.label_nameStatus)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.formLayout.setObjectName("formLayout")
        self.checkB_statusOff = QtWidgets.QCheckBox(Form)
        self.checkB_statusOff.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkB_statusOff.setObjectName("checkB_statusOff")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.checkB_statusOff)
        self.checkB_statusOn = QtWidgets.QCheckBox(Form)
        self.checkB_statusOn.setObjectName("checkB_statusOn")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.checkB_statusOn)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_save = QtWidgets.QPushButton(Form)
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout.addWidget(self.btn_save)
        self.btn_cancel = QtWidgets.QPushButton(Form)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout.addWidget(self.btn_cancel)
        self.verticalLayout_3.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Настроики"))
        self.label_name.setText(_translate("Form", "TextLabel"))
        self.checkB_statusOff.setText(_translate("Form", "Уволен"))
        self.checkB_statusOn.setText(_translate("Form", "Активен            "))
        self.btn_save.setText(_translate("Form", "ОК"))
        self.btn_cancel.setText(_translate("Form", "Отмена"))
