# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './View/main_container/setting_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(512, 688)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_name = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_name.setFont(font)
        self.label_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_name.setObjectName("label_name")
        self.verticalLayout_3.addWidget(self.label_name)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_branch = QtWidgets.QWidget()
        self.tab_branch.setObjectName("tab_branch")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_branch)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkB_branch = QtWidgets.QCheckBox(self.tab_branch)
        self.checkB_branch.setObjectName("checkB_branch")
        self.verticalLayout.addWidget(self.checkB_branch)
        self.tW_branch = QtWidgets.QTableWidget(self.tab_branch)
        self.tW_branch.setStyleSheet("QTableWidget\n"
"{ \n"
"background-color: white; \n"
"border: 0px solid #3873d9;\n"
"}")
        self.tW_branch.setShowGrid(False)
        self.tW_branch.setObjectName("tW_branch")
        self.tW_branch.setColumnCount(0)
        self.tW_branch.setRowCount(0)
        self.verticalLayout.addWidget(self.tW_branch)
        self.tabWidget.addTab(self.tab_branch, "")
        self.tab_department = QtWidgets.QWidget()
        self.tab_department.setObjectName("tab_department")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_department)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkB_department = QtWidgets.QCheckBox(self.tab_department)
        self.checkB_department.setObjectName("checkB_department")
        self.verticalLayout_2.addWidget(self.checkB_department)
        self.tW_department = QtWidgets.QTableWidget(self.tab_department)
        self.tW_department.setEnabled(True)
        self.tW_department.setStyleSheet("QTableWidget\n"
"{ \n"
"background-color: white; \n"
"border: 0px solid #3873d9;\n"
"}")
        self.tW_department.setShowGrid(False)
        self.tW_department.setObjectName("tW_department")
        self.tW_department.setColumnCount(0)
        self.tW_department.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tW_department)
        self.tabWidget.addTab(self.tab_department, "")
        self.tab_system = QtWidgets.QWidget()
        self.tab_system.setObjectName("tab_system")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_system)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.checkB_system = QtWidgets.QCheckBox(self.tab_system)
        self.checkB_system.setObjectName("checkB_system")
        self.verticalLayout_5.addWidget(self.checkB_system)
        self.tW_system = QtWidgets.QTableWidget(self.tab_system)
        self.tW_system.setStyleSheet("QTableWidget\n"
"{ \n"
"background-color: white; \n"
"border: 0px solid #3873d9;\n"
"}")
        self.tW_system.setShowGrid(False)
        self.tW_system.setObjectName("tW_system")
        self.tW_system.setColumnCount(0)
        self.tW_system.setRowCount(0)
        self.verticalLayout_5.addWidget(self.tW_system)
        self.tabWidget.addTab(self.tab_system, "")
        self.tab_szi = QtWidgets.QWidget()
        self.tab_szi.setObjectName("tab_szi")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_szi)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.checkB_szi = QtWidgets.QCheckBox(self.tab_szi)
        self.checkB_szi.setObjectName("checkB_szi")
        self.verticalLayout_6.addWidget(self.checkB_szi)
        self.tW_szi = QtWidgets.QTableWidget(self.tab_szi)
        self.tW_szi.setStyleSheet("QTableWidget\n"
"{ \n"
"background-color: white; \n"
"border: 0px solid #3873d9;\n"
"}")
        self.tW_szi.setShowGrid(False)
        self.tW_szi.setObjectName("tW_szi")
        self.tW_szi.setColumnCount(0)
        self.tW_szi.setRowCount(0)
        self.verticalLayout_6.addWidget(self.tW_szi)
        self.tabWidget.addTab(self.tab_szi, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.label_nameStatus = QtWidgets.QLabel(Form)
        self.label_nameStatus.setText("")
        self.label_nameStatus.setObjectName("label_nameStatus")
        self.verticalLayout_3.addWidget(self.label_nameStatus)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.formLayout.setObjectName("formLayout")
        self.checkB_statusOff = QtWidgets.QCheckBox(Form)
        self.checkB_statusOff.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkB_statusOff.setObjectName("checkB_statusOff")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.checkB_statusOff)
        self.checkB_statusOn = QtWidgets.QCheckBox(Form)
        self.checkB_statusOn.setObjectName("checkB_statusOn")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.checkB_statusOn)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_save = QtWidgets.QPushButton(Form)
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout.addWidget(self.btn_save)
        self.btn_cancel = QtWidgets.QPushButton(Form)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout.addWidget(self.btn_cancel)
        self.verticalLayout_3.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Настроики"))
        self.label_name.setText(_translate("Form", "TextLabel"))
        self.checkB_branch.setText(_translate("Form", "Все филиалы"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_branch), _translate("Form", "Филиал"))
        self.checkB_department.setText(_translate("Form", "Все службы"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_department), _translate("Form", "Служба"))
        self.checkB_system.setText(_translate("Form", "Все системы"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_system), _translate("Form", "Системы"))
        self.checkB_szi.setText(_translate("Form", "Все СЗИ"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_szi), _translate("Form", "СЗИ"))
        self.checkB_statusOff.setText(_translate("Form", "Уволен"))
        self.checkB_statusOn.setText(_translate("Form", "Активен            "))
        self.btn_save.setText(_translate("Form", "ОК"))
        self.btn_cancel.setText(_translate("Form", "Отмена"))
