# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'View/Start_menu/Start_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(220, 220)
        MainWindow.setMinimumSize(QtCore.QSize(220, 220))
        MainWindow.setMaximumSize(QtCore.QSize(220, 220))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_user = QtWidgets.QPushButton(self.centralwidget)
        self.btn_user.setObjectName("btn_user")
        self.verticalLayout.addWidget(self.btn_user)
        self.btn_usb = QtWidgets.QPushButton(self.centralwidget)
        self.btn_usb.setObjectName("btn_usb")
        self.verticalLayout.addWidget(self.btn_usb)
        self.btn_equipment = QtWidgets.QPushButton(self.centralwidget)
        self.btn_equipment.setObjectName("btn_equipment")
        self.verticalLayout.addWidget(self.btn_equipment)
        self.btn_skr = QtWidgets.QPushButton(self.centralwidget)
        self.btn_skr.setObjectName("btn_skr")
        self.verticalLayout.addWidget(self.btn_skr)
        self.btn_szi = QtWidgets.QPushButton(self.centralwidget)
        self.btn_szi.setObjectName("btn_szi")
        self.verticalLayout.addWidget(self.btn_szi)
        self.btn_system = QtWidgets.QPushButton(self.centralwidget)
        self.btn_system.setObjectName("btn_system")
        self.verticalLayout.addWidget(self.btn_system)
        self.btn_setting = QtWidgets.QPushButton(self.centralwidget)
        self.btn_setting.setObjectName("btn_setting")
        self.verticalLayout.addWidget(self.btn_setting)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Helper"))
        self.btn_user.setText(_translate("MainWindow", "Пользователи"))
        self.btn_usb.setText(_translate("MainWindow", "USB устройства"))
        self.btn_equipment.setText(_translate("MainWindow", "Оргтехника"))
        self.btn_skr.setText(_translate("MainWindow", "СКР"))
        self.btn_szi.setText(_translate("MainWindow", "СЗИ"))
        self.btn_system.setText(_translate("MainWindow", "Информационные системы"))
        self.btn_setting.setText(_translate("MainWindow", "Настройки"))
